local COMP_TYPE_FUNC = 0
local COMP_TYPE_MEM = 2
local VTYPE_F64 = 0x7C
local VTYPE_F32 = 0x7D
local VTYPE_I64 = 0x7E
local VTYPE_I32 = 0x7F
local BLOCK_TYPE_EMPTY = 0x80

return {
  COMP_TYPE_FUNC = COMP_TYPE_FUNC,
  COMP_TYPE_MEM = COMP_TYPE_MEM,
  VTYPE_F64 = VTYPE_F64,
  VTYPE_F32 = VTYPE_F32,
  VTYPE_I64 = VTYPE_I64,
  VTYPE_I32 = VTYPE_I32,
  BLOCK_TYPE_EMPTY = BLOCK_TYPE_EMPTY
}