local COMP_TYPE_MEM = 2
local VTYPE_F64 = 0x7C
local VTYPE_F32 = 0x7D
local VTYPE_I64 = 0x7E
local VTYPE_I32 = 0x7F
local HTYPE_EXN = 0x69
local RTYPE_NULL = 0xD0
local RTYPE_FUNC = 0xD2
local BLOCK_TYPE_EMPTY = 0x80
local CTYPE_CATCH = 0
local CTYPE_CATCH_REF = 1
local CTYPE_CATCH_ALL = 2
local CTYPE_CATCH_ALL_REF = 3

return {
  COMP_TYPE_MEM = COMP_TYPE_MEM,
  VTYPE_F64 = VTYPE_F64,
  VTYPE_F32 = VTYPE_F32,
  VTYPE_I64 = VTYPE_I64,
  VTYPE_I32 = VTYPE_I32,
  HTYPE_EXN = HTYPE_EXN,
  RTYPE_FUNC = RTYPE_FUNC,
  RTYPE_NULL = RTYPE_NULL,
  BLOCK_TYPE_EMPTY = BLOCK_TYPE_EMPTY,
  CTYPE_CATCH = CTYPE_CATCH,
  CTYPE_CATCH_REF = CTYPE_CATCH_REF,
  CTYPE_CATCH_ALL = CTYPE_CATCH_ALL,
  CTYPE_CATCH_ALL_REF = CTYPE_CATCH_ALL_REF,
}